/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbz_Context */

#ifndef _Included_com_cbz_Context
#define _Included_com_cbz_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbz_Context
 * Method:    connect
 * Signature: ([Lcom/cbz/Host;I)[Lcom/cbz/Node;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cbz_Context_connect
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_cbz_Context
 * Method:    ping
 * Signature: ([Lcom/cbz/Node;Ljava/lang/String;I)[Lcom/cbz/Ping;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cbz_Context_ping
  (JNIEnv *, jobject, jobjectArray, jstring, jint);

/*
 * Class:     com_cbz_Context
 * Method:    pong
 * Signature: ([Lcom/cbz/Node;I)[Lcom/cbz/Pong;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cbz_Context_pong
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
