/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbz_Node */

#ifndef _Included_com_cbz_Node
#define _Included_com_cbz_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbz_Node
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cbz_Node_disconnect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
